### PR TITLE
Add ICS schedules for UK and AET meetings

### PR DESCRIPTION
**Pull request by ross-spencer**
A proposal to add an ICS calendar to the repository for AET and GMT times based on the drop-in.md file. The text in the drop-in MD file has been updated so that it is easier to maintain and only links to the calendar file. 

NB. `.ics` is plain-text and we might want to review it further to see if there are any customization anyone thinks would be a good idea. The calendar was created using: http://ical.marudot.com/

NB. UK and AET times have been transposed to CET times but should be the same, but it would be helpful if folks can confirm. 

The modified README.md can be better reviewed [here](https://github.com/digital-preservation/PRONOM_Research/blob/8dfb03dcdfea1ba3a2709e644b03c5f0965e99e3/Resources/drop-in.md).

### CODE REVIEW

**Comment by richardlehane** [comment]
tested and works OK if you click on the download button [image: image.png]

Suggest adding the URL to the description field as well (in Outlook it just
said the location was "Online" without any link to the Teams call)

**Comment by ross-spencer** [comment]
> Suggest adding the URL to the description field as well (in Outlook it just said the location was "Online" without any link to the Teams call)
 
Totally - will make it so. Definitely some difference between calendar approaches here.

**Comment by ross-spencer** [comment]
cc @AndreaHri @tnafrancesca @andreykotov91 following on from yesterday, this commit adds a calendar entry that folks may use for the two times. The calendar will simply repeat until a user opts to delete it. Perhaps some text around that may be helpful? Otherwise, in the calendar entry folks will also find a simple description and as Richard suggested, the URL to the teams meeting.

**Review by tnafrancesca — APPROVED** [review]

**Comment by tnafrancesca** [comment]
This is great- thank you so much @ross-spencer . Changes made are clickable links to add the PRONOM Open Drop-In dates to personal calendars

**Comment by prettybits** [comment]
@ross-spencer I just had a closer look at the URL in the iCalendar files as I had trouble yesterday joining the meeting by following the link in the calendar event. It looks like the URL has been double percent-encoded, so my browser after decoding still tries an invalid URL and is redirected by Teams to an error page.

Current value: `https://teams.microsoft.com/l/meetup-join/19%253ameeting_OThkMzIwMWItYTUzYS00NDIxLTgzNTEtMzAwMGQzYWZhNmJi%2540thread.v2/0?context=%257b%2522Tid%2522%253a%2522f99512c1-fd9f-4475-9896-9a0b3cdc50ec%2522%252c%2522Oid%2522%253a%2522e02319b9-2b3a-4408-86ee-7cd0ba62ed9f%2522%257d`

After decoding: `https://teams.microsoft.com/l/meetup-join/19%3ameeting_OThkMzIwMWItYTUzYS00NDIxLTgzNTEtMzAwMGQzYWZhNmJi%40thread.v2/0?context=%7b%22Tid%22%3a%22f99512c1-fd9f-4475-9896-9a0b3cdc50ec%22%2c%22Oid%22%3a%22e02319b9-2b3a-4408-86ee-7cd0ba62ed9f%22%7d`

Decoding a second time gives `https://teams.microsoft.com/l/meetup-join/19:meeting_OThkMzIwMWItYTUzYS00NDIxLTgzNTEtMzAwMGQzYWZhNmJi@thread.v2/0?context={"Tid":"f99512c1-fd9f-4475-9896-9a0b3cdc50ec","Oid":"e02319b9-2b3a-4408-86ee-7cd0ba62ed9f"}` which is the link also used in the document which ultimately worked.

I think this happened because the generator you used unconditionally encodes the URL you put there, but when copying a link target from the browser it already gives you an encoded URL, leading to the double encoding issue. I can open a PR for this if you don't see an issue with my analysis?

**Comment by ross-spencer** [comment]
@prettybits that sounds messy. if you can clean it up then please go for it!

**Pull request merged**
